name: spt-diffusion2
channels:
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py310h06a4308_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - comm=0.2.3=py310h06a4308_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - freetype=2.14.1=hf5b9546_0
  - icu=73.1=h6a678d5_0
  - imageio=2.37.2=py310h7040dfc_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.8.0=py310h06a4308_0
  - jupyter_core=5.9.1=py310h06a4308_0
  - lazy_loader=0.4=py310h06a4308_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.54=hee55ce4_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.4.2=py310h06a4308_0
  - numpy=2.2.5=py310h64c44e4_2
  - numpy-base=2.2.5=py310he1678cf_2
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=py310h06a4308_1
  - parso=0.8.5=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_1
  - pillow=11.1.0=py310hac6e08b_1
  - platformdirs=4.5.0=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - pyzmq=27.1.0=py310hcf8288c_1
  - readline=8.3=hc2a1206_0
  - scikit-image=0.25.2=py310h86c3e14_1
  - scipy=1.15.3=py310h0a862cd_1
  - setuptools=80.10.2=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py310h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tifffile=2025.2.18=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025c=he532380_0
  - wcwidth=0.2.14=py310h06a4308_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - matplotlib==3.10.8
      - pip==26.0.1
      - pyparsing==3.3.2
      - tqdm==4.67.3